---
title: Mariemont Community Church
timezone: America/New_York
collections:
  people:
    title: People
    output: false
  posts:
    title: Posts
    output: true
  sermons:
    title: Sermons
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: sermons
  values:
    layout: page-sermon
    series: ''
    week: ''
    sermon_date: ''
    sermon_bg: "/uploads/sermon_bg.jpg"
    speaker: ''
    bible_text: ''
    excerpt: ''
    audio_file: ''
    audio_file_length: 0
    video_url: ''
    brochure_file: ''
    thumbnail_image: ''
- scope:
    path: ''
    type: pages
  values:
    is_ministry: false
    bg_color: ''
    hero_image: ''
    hasHero: false
    hasDownload: false
    download:
      file: 
      info: 
      cta: 
    heading: ''
    lead_in: ''
- scope:
    path: ''
    type: people
  values:
    name: ''
    is_elder: false
    image: ''
    position: ''
email: mark@mariemontchurch.org
description: We are a growing community of families in East Cincinnati united by our
  commitment to follow Jesus.
baseurl: 
url: https://mariemontchurch.org
markdown: kramdown
highlighter: rouge
plugins_dir: plugins
plugins:
- jekyll-seo-tag
port: 7000
permalink: "/:categories/:title/"
sass:
  sass_dir: "/assets/stylesheets"
  style: compressed
podcast_url: http://www.mariemontchurch.org/podcast.rss
podcast_album_art: 
podcast_title: Mariemont Community Church Sunday Teaching
podcast_owner: Terri Cofsky
podcast_email: terri@mariemontchurch.org
podcast_author: Denis Beausejour
podcast_description: 
podcast_summary: 
podcast_subtitle: 
podcast_copyright: "&#x2117; &amp; &#xA9; 2019"
podcast_keyworkds: Mariemont Community
