---
title: Mariemont Community Church
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  staff:
    title: Staff
    output: false
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: We are a growing community of families in East Cincinnati united by our
  commitment to follow Jesus.
baseurl: ''
url: http://mariemontchurch.org
twitter_username: changeme
github_username: changeme
markdown: kramdown
highlighter: rouge
gems:
- jekyll-seo-tag
port: 8000
